require('user/options')
require('user/lualine')
require('user/autopairs')
require('user/bufferline')
require('user/telescope')
require('user/gitsigns')
require('user/nvim-tree')
require('user/toggleterm')
require('user/keymaps')
require('user/lsp')
require('user/formatting')
require('lspfuzzy').setup { }
require('user/treesitter')
require('user/indentline')
require('user/notify')
require('user/numb')
require('user/spectre')
